version: '3.18'
services:
  postgres:
    container_name: ${CONTAINER_POSTGRES_NAME}
    image: ${IMAGE_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_dev_12:/var/lib/postgresql/data
    networks:
      - postgres_network_dev_12
    restart: unless-stopped

  pgadmin:
    container_name: ${CONTAINER_PG_NAME}
    image: ${IMAGE_PG}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - postgres_network_dev_12
    restart: unless-stopped

networks:
  postgres_network_dev_12:
    driver: bridge

volumes:
  postgres_data_dev_12:
  pgadmin:
